### ISSUE TITLE
Unnecessary by-ref assignments

### ISSUE THREAD

**Issue by cmb69** [manu37/tinymce4#10]
The [assignments by reference of `$pcf` and `$ptx`](https://github.com/manu37/tinymce4/blob/86f5a318d359d57daf2e4ffc59c5c7aba0639924/init.php#L151-L152) are unnecessary, and may be harmful with regard to performance, see https://schlueters.de/blog/archives/181-More-on-references.html.

They also raise a notice in case the [arrays are replaced by objects](https://cmsimpleforum.com/viewtopic.php?f=29&t=12012#p55639).

**Comment by manu37** [comment]
Do you have another idea to shorten these extending long filenames to comply our PEAR Standards (not to write overlong lines)? Going with a local function ( `function pcf("$plugin_cf['tinymce4'][index]")`;)?

**Comment by cmb69** [comment]
> Do you have another idea to shorten these extending long filenames to comply our PEAR Standards (not to write overlong lines)?

Assigning to a local variable is fine (not only with regard to readability, but also it is a slight performance improvement):
````
$pcf = $plugin_cf['tinymce4'];
````
It's just that the reference assignment (`=&`) is unnecessary, and would cause notices, if cmsimple-xh/cmsimple-xh#192 will be merged.

> Going with a local function ( function pcf("$plugin_cf['tinymce4'][index]");)?

There are no function local functions in PHP. Although you can nest function definitions, e.g.:
````
function foo() {
    function bar() {
        echo 'hi';
    }
}
`````
`bar()` can be called from outside of `foo` as soon as `foo()` has been called once.
