### ISSUE TITLE
I18n doesn't work for CDN variant

### ISSUE THREAD

**Issue by cmb69** [manu37/tinymce4#11]
If TinyMCE is loaded from CDN, the text (for instance, the toolbar button's labels) are always in English. It seems that is being caused by the missing `language` option; the documentation on [`language_url`](https://www.tinymce.com/docs/configure/localization/#language_url) states:
> When using the language option to set the user interface language you may choose to place any language pack(s) in a directory other than the default.

**Comment by cmb69** [comment]
Note that this appears to affect only `external_plugins`.

**Comment by manu37** [comment]
I18n works well in the CND Variant. Although the language files (other than en have to be present in tinymce4/tinymce/langs/ (as they are in the CDN Variant downloadable). How the language files of extra plugins are implemented I don't know. Don't they follow the path as stated in "external_plugins"?

**Comment by cmb69** [comment]
> Don't they follow the path as stated in "external_plugins"?

It seems to me the issue is that the language would have to be declared. I've slightly modified the [example plugin](https://www.tinymce.com/docs/advanced/creating-a-plugin/) (because apparently external_plugins which are alread in CDN are not loaded from the given location):

[example1.zip](https://github.com/manu37/tinymce4/files/926088/example1.zip)

In a German CMSimple_XH the button's label is "My button". If I modify init.js to also emit the "language" property (besides the "language_url" property), the button's label is correctly displayed as "Mein Schalter".

**Comment by manu37** [comment]
Should work now. See: https://github.com/cmsimple-xh/cmsimple-xh/commit/6ca4de28d3f331218d6b534972e54157cf0bbd67

**Comment by cmb69** [comment]
Yes, works fine now. Thanks!
