### ISSUE TITLE
Update bundled TinyMCE

### ISSUE THREAD

**Issue by cmb69** [manu37/tinymce4#12]
Currently, [version 4.5.3 is bundled](https://github.com/manu37/tinymce4/blob/42fdc0a25eeddaeb351901f4722a4c72ff7a01c3/tinymce/tinymce.min.js#L1), but there are some bugs which are fixed in newer versions (see, for instance, https://cmsimpleforum.com/viewtopic.php?f=10&t=12706), so updating to latest TinyMCE would be helpful.

**Comment by manu37** [comment]
Yes, I can. But be aware that issue #8 is still pending.

**Comment by cmb69** [comment]
I had [applied the suggested workaround](https://github.com/cmsimple-xh/cmsimple-xh/commit/c8cdf95056e366e83f0b76037e11b1c2c57beecb#diff-e303071500d8bc4ad07bc3152faf56af) as preliminary fix. Unless the issue will be solved for TinyMCE soon, we probably have to use this workaround (at least for XH 1.7, where HTML comments will always appear in advanced mode).

**Comment by manu37** [comment]
update to v4.6.0 fullfilled.  issue [#8](https://github.com/manu37/tinymce4/issues/8) seems to be resolved.
