### ISSUE TITLE
Load-Fehler

### ISSUE THREAD

**Issue by ghost** [manu37/tinymce4#15]
1.  Nach der Installation auf xH 1.6.10 erhalte ich den Fehler 'Failed to load content css: http://cdn.tinymce.com/4/%BASE_URL%/templates/mini2/stylesheet.css'

In required-classes.php steht :

/define('TINYMCE4_VARIANT', ''); //TinyMCE4 fully installed
define('TINYMCE4_VARIANT', 'CDN'); //TinyMCE4 externally loaded
define('TINYMCE4_CDN_ORIG', '//cdn.tinymce.com/4/tinymce.min.js'); //TinyMCE4 externally loaded

Wo muss ich patchen ?

2. Die schwarzen Icons sind nicht jedermanns Sache. Kann man nicht einen Konfigurationspunkt machen, an dem man zwischen dem alten bunten und dem neuen grauschwarzen Menü umschalten kann ?

**Comment by manu37** [comment]
Welche tinymce4 Version hast Du?
Was steht in Deiner init_*.js Datei bei content_css? Da sollte stehen:
`content_css: "%STYLESHEET%",`.

**Comment by manu37** [comment]
zu 2.: die farbige toolbar gibts bei Version 4 nicht mehr, weil die Icons aus einem font und nicht aus grafiken generiert werden.

**Comment by manu37** [comment]
Laut https://github.com/cmsimple-xh/cmsimple-xh/issues/206#issuecomment-294887976 solltest Du auch die aktuelle CDN Source eintragen.

**Comment by ghost** [comment]
content_css: "%STYLESHEET%",. steht auch da - neuste Version vom sourceforge

Das Problem ist , daß früher der Vorschlag eines Eintrags    document_base_url: "%BASE_URL%"  helfen konnte. Man kann diese Base url doch dort irgendwie eintragen, dann geht er gar nicht aufs Web. 
Man könnte das doch mal implementieren.
-----------------------------------------------------------
Zu den Skins 👍 http://tinymceplugins.com/catalog/skins
und            http://skin.tinymce.com/ 
bzw. https://www.tinymce.com/docs/advanced/creating-a-skin

**Comment by manu37** [comment]
Sorry, verstehe weiterhin nur Bahnhof.
Beantworte doch bitte mal die [gestellten Fragen](https://github.com/manu37/tinymce4/issues/15#issuecomment-317162844). 
Was beabsichtigst Du mit %BASE_URL% in der init_*.js? (Dieser Schlüssel wird nirgends gerendered).
Du verwendest die [CDN Version](https://github.com/manu37/tinymce4/issues/15#issue-244821382), möchtest aber "gar nicht aufs Web"?
Bei den skins steht es Dir ja frei, einen eigenen skin zu integrieren. Nur werden die icons wohl monochrom bleiben.

**Comment by cmb69** [comment]
> Was beabsichtigst Du mit %BASE_URL% in der init_*.js? (Dieser Schlüssel wird nirgends gerendered).

Ich vermute hier geht es um einen Clean-URL-Mod. Siehe "Missing stylesheet for the editor" unter https://cmsimpleforum.com/viewtopic.php?f=4&t=5719.

**Comment by ghost** [comment]
Der Fehler hiess   http://cdn.tinymce.com/4/%BASE_URL%/templates/mini2/stylesheet.css'
Die Software will also aufs Web. Das kann man doch irgendwie umlenken.
Ich habe aber noch einen anderen Fehler: 
Failed to load content css: http://localhost/xh1610clean/News01/templates/bsp_acme_ForTop/stylesheet.css    -- News01 ist die übergeordnete Seite zur geöffneten : News01/acme1
 
Das tinymce4 ist allerdings im Verzeichnis tinymce4 installiert und der tinymce35 im Verzeichnis tinymce.
Wenn es keine einfache Lösung gibt lösche ich den tinymce4 und bleibe beim 3.5. Der Ckeditor 4 ist auch für die Bildeinbettung um Klassen besser nur span't er wild. Hoffentlich liegt es nicht auch an der cleanen Version von 1.6.10.

**Comment by manu37** [comment]
@gvoxcms Lade mal den aktuellen tinyMCE4 von [hier](https://sourceforge.net/projects/tinymce4cmsimplexh/) herunter. Sieh zu, dass in der config "CDN" nicht ausgewählt ist. Dann läuft der tinyMCE4 ganz lokal und die Pfadangaben sind alle relativ.

**Comment by ghost** [comment]
Ich habe genau die Version 4.1.30 vom Sourceforge. Der Fehler ist weiter
Failed to load content css: http://localhost/xh1610clean/Download/templates/mini2/stylesheet.css
Tinymce im Verzeichnis tinymce geht - tinymce im Verzeichnis tinymce4 geht nicht(xamp!). Natürlich habe ich kein CDN ausgewählt und schon dreimal neu entpackt. Ich habe auch im Clean manchmal den Fehler: keine Seite ausgewählt. Im Original xh1610 habe ich andere Pfadfehler. Evtl. liegt es am Xamp - nur tinymce 3.5 und ckeditor machen das nicht. Damit wollen wir es belassen.
