### ISSUE TITLE
xhplugincall/plugin.js missing

### ISSUE THREAD

**Issue by cmb69** [manu37/tinymce4#21]
I'd like to suggest to have an unminified version of [xhplugincall/plugin.min.js](https://github.com/manu37/tinymce4/blob/master/tinymce/plugins/xhplugincall/plugin.min.js) in this repo, to make it easier to view diffs (for instance, on PRs).

**Comment by manu37** [comment]
yes, but when tinymce.min.js is called all the plugins are loaded accordingly. Therefore I will leave plugin.min.js unminified during developement.

**Comment by cmb69** [comment]
Great. Thanks!
