### ISSUE TITLE
Plugin administration can't be accessed under XH 1.7

### ISSUE THREAD

**Issue by cmb69** [manu37/tinymce4#7]
I've just noticed that the plugin administration of TinyMCE 4 (and also TinyMCE 3, BTW) can't be accessed anymore under recent CMSimple_XH 1.7. That's been caused by cmsimple-xh/cmsimple-xh#22. [`initvar()` in combination with checking for the value to be truthy](https://github.com/manu37/tinymce4/blob/86f5a318d359d57daf2e4ffc59c5c7aba0639924/admin.php#L40-L42) isn't sufficient, because `$tinymce===''` (before this change in CMSimple_XH, the `initvar()` has been a no-op, by the way).

I suggest to use [`XH_wantsPluginAdministration()`](http://www.cmsimple-xh.org/dev-doc/php/XH/_cmsimple---adminfuncs.php.html#functionXH_wantsPluginAdministration) for the check.

**Comment by manu37** [comment]
Now is there a new way to sanitize SERVER variables like $admin & $action or do I have to do it by hand like in the old days?

**Comment by manu37** [comment]
> the initvar() has been a no-op, by the way

verstehe nur Bahnhof, but initvar() is still alive, isn't it?

**Comment by cmb69** [comment]
> Now is there a new way to sanitize SERVER variables like $admin & $action or do I have to do it by hand like in the old days?

No, there is no new way. However, I don't think that it is necessary to santize `$admin` and `$action`. Just compare them to a white-list, and do the default action for everything else. See, for instance, [how it's done in Pagemanager](https://github.com/cmb69/pagemanager_xh/blob/c0fb85b6851563fe54732054fba165eb3e1c7c0b/classes/Plugin.php#L52-L64).

If you need to sanitize other variables consider using the [filter extension](http://php.net/manual/en/book.filter.php) (I suppose that it is generally available). The API is, however, terrible, IMHO.

> verstehe nur Bahnhof, but initvar() is still alive, isn't it?

Yes, initvar() still exists, unfortunately, but killing it would be too much of a backward compatibility break, but [deprecating it might be appropriate](https://github.com/cmsimple-xh/cmsimple-xh/issues/201). What I've meant above, is that initvar('pluginname') has been unnecessary in earlier CMSimple(_XH) versions, because $pluginame [has already been initialized before](https://github.com/cmsimple-xh/cmsimple-xh/blob/1.6.9/cmsimple/cms.php#L806-L810), but calling initvar() on an already initialized variable [does nothing](https://github.com/cmsimple-xh/cmsimple-xh/blob/1.6.9/cmsimple/functions.php#L569-L577).
