### ISSUE TITLE
In advanced split mode TinyMCE throws error

### ISSUE THREAD

**Issue by cmb69** [manu37/tinymce4#8]
As soon as there's a HTML comment in the source-code to be edited (which is always the case in advanced split mode, where the split marker is sent to the editor), TinyMCE throws:
````
Uncaught TypeError: Cannot read property 'fontFamily' of undefined
````
That doesn't seem to happen with TinyMCE 4.5.0, but with 4.5.3 and 4.5.5, However, the [official TinyMCE demo](https://www.tinymce.com/docs/demo/full-featured/) doesn't appear to have this issue.

See also https://cmsimpleforum.com/viewtopic.php?f=16&t=6453&start=60#p58735 ff.

**Comment by manu37** [comment]
> However, the official TinyMCE demo doesn't appear to have this issue.

Yes it does: http://codepen.io/manu37/pen/WjoogZ .
Bug report is here: https://github.com/tinymce/tinymce/issues/3603

**Comment by manu37** [comment]
After a 1st test with v4.6.0 the issue seems to be resolved. Please verify.

**Comment by cmb69** [comment]
Yes, appears to be fine now, thanks!
